datasets:
  # - name: doof-ferb/vlsp2020_vinai_100h
  #   text_column: transcription
  #   audio_column: audio
  #   split: train
  - name: giangndm/demo-tts-synthetic
    subset: vivoice_24000_0 # vietnamese voice
    split: train
    text_column: text
    audio_column: audio
  - name: giangndm/demo-tts-synthetic
    subset: chatgpt-paraphrases-simple_24000_0 # english voice
    split: train
    text_column: text
    audio_column: audio

model_config: ./configs/qwen3_4b.yaml
model_template: ./configs/qwen3.template
training:
  output_dir: ./checkpoints/qwen3_4b
  num_train_epochs: 2
  per_device_train_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  logging_steps: 10
  save_steps: 1000
  audio_dump_steps: 1000
  audio_dump_num_samples: 2
  seed: 42
