datasets:
  # - name: doof-ferb/vlsp2020_vinai_100h
  #   text_column: transcription
  #   audio_column: audio
  #   split: train
  - name: giangndm/demo-tts-synthetic
    subset: vivoice_24000_0 # vietnamese voice
    split: train
    text_column: text
    audio_column: audio
  - name: giangndm/demo-tts-synthetic
    subset: chatgpt-paraphrases-simple_24000_0 # english voice
    split: train
    text_column: text
    audio_column: audio

model_config: ./configs/Qwen3-0.6B-Instruct.yaml
training:
  output_dir: ./checkpoints/Qwen3-0.6B-Instruct
  num_train_epochs: 20
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 8
  learning_rate: 1e-3
  weight_decay: 0.01
  llm_loss_weight: 5.0
  tts_loss_weight: 1.0
  warmup_ratio: 0.1
  logging_steps: 10
  save_steps: 1000
  keep_last_n_checkpoints: 10
  audio_dump_steps: 1000
  audio_dump_num_samples: 10
  seed: 42
